services:
  - type: web
    name: pepertect-ws
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: UPSTOX_ACCESS_TOKEN
        sync: false
      - key: UPSTOX_API_KEY
        sync: false
      - key: UPSTOX_API_SECRET
        sync: false